---
title: "Untitled"
author: "RN7"
date: "7/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Statsbomb



```{r, message=FALSE}
library(soccermatics) ## soccermatics viz package
library(StatsBombR)   ## statsbomb R package to grab free statsbomb data!
library(dplyr)        ## data wrangling
library(tidyr)        ## data wrangling
library(purrr)        ## data wrangling and iteration
library(stringr)      ## data wrangling
library(rvest)        ## webscraping
library(polite)       ## webscraping (Github only pkg)
library(ggplot2)      ## plotting
library(scales)       ## plotting scales
library(ggimage)      ## images for flags
library(ggforce)      ## plotting text labels
library(cowplot)      ## plotting grid
library(glue)         ## text
library(ggrepel)      ## plotting text labels
library(magick)       ## plotting
library(ggtextures)   ## soccer ball emoji as geom_col()
library(extrafont)    ## fonts: Roboto Condensed

loadfonts()
```



```{r}
comps <- FreeCompetitions()
comps %>% 
  filter(competition_id == 72)

StatsBombR:::MatchesDF

all_free <- StatsBombFreeEvents(MatchesDF = 22961)

wwc_matches <- FreeMatches(Competitions = 72)

wwc_final_id <- wwc_matches %>% filter(match_id == 69321)

wwc_final_raw <- get.matchFree(Match = wwc_final_id)

glimpse(wwc_final_raw)
```

```{r}
saveRDS(wwc_final_raw, file = here::here("data/wwc_final_raw.RDS"))

wwc_final_raw <- readRDS(file = here::here("data/wwc_final_raw.RDS"))
```




## PASS MAP (Complete + Incomplete)

### USA 


```{r, fig.height=10, fig.width=16}
d3 <- wwc_final_raw %>% 
  cleanlocations() %>% 
  soccerTransform(method = "statsbomb") %>% 
  filter(type.name == "Pass" & team.name == "United States Women's") %>% 
  mutate(pass.outcome = as.factor(if_else(is.na(pass.outcome.name), 
                                          "Complete", "Incomplete")))

pass_map_neth <- soccerPitch(arrow = "r",
            title = "USA W (vs. Netherlands W)", 
            subtitle = "Pass map") +
  geom_segment(data = d3, aes(x = location.x, xend = pass.end_location.x, 
                              y = location.y, yend = pass.end_location.y, 
                              col = pass.outcome), alpha = 0.75) +
  geom_point(data = d3, aes(x = location.x, y = location.y, 
                            col = pass.outcome), alpha = 0.5) +
  scale_color_manual(values = c("blue", "red"), name = "Outcome") +
  theme(text = element_text(family = "Roboto Condensed"),
        legend.position = "bottom")

# Pass map (to first substitution)
usa_passmap <- wwc_final_raw %>% 
  cleanlocations() %>% 
  soccerTransform(method = "statsbomb") %>% 
  filter(team.name == "United States Women's") %>% 
  soccerPassmap(theme = "light")



pass_map_text <- ggplot() +
  annotate(geom = "text", family = "Roboto Condensed",
           label = str_wrap("USA use the wide areas to attack but most of their crosses into the box were unsucessful. Their big chances (especially after the first goal was scored) came from the times they were able to break through the previously packed Dutch midfield which started to leave gaps as they pushed up to create an equalizer.",
                            width = 50), size = 6,
           x = 1, y = 1) +
  theme_void()

library(patchwork)

usa_passmap / (pass_map_neth + pass_map_text)


pass_map_neth + pass_map_text - usa_passmap + plot_layout(ncol = 1)
```

```{r}
ggsave(filename = here::here("Women's World Cup 2019/output/usa_passmap.png"),
       height = 10, width = 16)
```


### Netherlands


```{r, fig.height=10, fig.width=16}
d4 <- wwc_final_raw %>% 
  cleanlocations() %>% 
  soccerTransform(method = "statsbomb") %>% 
  filter(type.name == "Pass" & team.name == "Netherlands Women's") %>% 
  mutate(pass.outcome = as.factor(if_else(is.na(pass.outcome.name), 
                                          "Complete", "Incomplete")))

pass_map_ned <- soccerPitch(arrow = "r",
            title = "Netherlands W (vs. USA W)", 
            subtitle = "Pass map") +
  geom_segment(data = d4, aes(x = location.x, xend = pass.end_location.x, 
                              y = location.y, yend = pass.end_location.y, 
                              col = pass.outcome), alpha = 0.75) +
  geom_point(data = d4, aes(x = location.x, y = location.y, 
                            col = pass.outcome), alpha = 0.5) +
  scale_color_manual(values = c("blue", "red"), name = "Outcome") +
  theme(text = element_text(family = "Roboto Condensed"),
        legend.position = "bottom")

# Pass map (to first substitution)
holland_passmap <- wwc_final_raw %>% 
  cleanlocations() %>% 
  soccerTransform(method = "statsbomb") %>% 
  filter(team.name == "Netherlands Women's") %>% 
  soccerPassmap(theme = "light")



pass_map_text_ned <- ggplot() +
  annotate(geom = "text", family = "Roboto Condensed",
           label = str_wrap("The Dutch cycled possession around their midfield three but could not find the creativity to play vertical passes centrally to star Striker Miedema or Berensteyn. Even when they did it was when they dropped very deep into midfield. The Dutch did not complete ANY passes in the USA's 18-yard box!",
                            width = 50), size = 6,
           x = 1, y = 1) +
  theme_void()

library(patchwork)

usa_passmap / (pass_map_neth + pass_map_text)


pass_map_ned + pass_map_text_ned - holland_passmap + plot_layout(ncol = 1)
```


```{r}
ggsave(filename = here::here("Women's World Cup 2019/output/ned_passmap.png"),
       height = 10, width = 16)
```








```{r}
wwc_final_raw %>% 
  cleanlocations() %>% 
  soccerTransform(method = "statsbomb") %>% 
  filter(type.name == "Pass" & team.name == "Netherlands Women's") %>% View()
  soccerPositionMap(id = "player.name", x = "location.x", y = "location.y", 
                    fill1 = "blue", grass = T,
                    arrow = "r", 
                    title = "Netherlands W (vs. USA W)", 
                    subtitle = "Average pass position (1' - )")
```

