---
title: "Untitled"
author: "RN7"
date: "8/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height=6, fig.width=8)
```

# Packages

```{r, message=FALSE, warning=FALSE}
pacman::p_load(dplyr, stringr, tidyr, purrr, forcats, ggplot2,
               StatsBombR, soccermatics, SBpitch, ggsoccer,
               rlang, extrafont, ggupset)
loadfonts()
```



```{r}
comps <- FreeCompetitions()

glimpse(comps)
```


# Raw data

```{r}
messi_matches_raw <- comps %>% 
  filter(competition_id ==11) %>% 
  FreeMatches()


messi_data_raw <- StatsBombFreeEvents(MatchesDF = messi_matches_raw)

glimpse(messi_data_raw)
```

# Save raw

```{r}
saveRDS(messi_data_raw, file = here::here("data/messi_data_raw.RDS"))
messi_data_raw <- readRDS(file = here::here("data/messi_data_raw.RDS"))
```


# Clean all + add season labels

```{r}
messi_data_clean <- messi_data_raw %>% 
  allclean() %>%  ## cleanlocations, goalkeeper, shot, freezeframe, defensive
  left_join(comps %>% select(season_id, season_name), by = "season_id")
```



```{r}
messi_data_clean <- messi_data_clean %>% 
  ## player name
  mutate(player.name = case_when(
    player.name == "Oleguer Presas Renom" ~ "Oleguer",
    player.name == "Xavier Hernández Creus" ~ "Xavi",
    player.name == "Carles Puyol i Saforcada" ~ "Carles Puyol",
    player.name == "Anderson Luís de Souza" ~ "Deco",
    player.name == "Rafael Márquez Álvarez" ~ "Rafa Márquez",
    player.name == "Giovanni van Bronckhorst" ~ "Gio v.Bronckhorst",
    player.name == "Samuel Eto'o Fils" ~ "Samuel Eto'o",
    player.name == "Víctor Valdés Arribas" ~ "Víctor Valdés",
    player.name == "Juliano Haus Belletti" ~ "Juliano Belletti",
    player.name == "Ludovic Giuly" ~ "Ludovic Giuly",
    player.name == "Andrés Iniesta Luján" ~ "Andrés Iniesta",
    player.name == "Ronaldo de Assis Moreira" ~ "Ronaldinho",
    player.name == "Lionel Andrés Messi Cuccittini" ~ "Lionel Messi",
    player.name == "Fernando Navarro i Corbacho" ~ "Fernando Navarro",
    player.name == "Sylvio Mendes Campos Junior" ~ "Sylvinho",
    player.name == "Damià Abella Pérez" ~ "Damià",
    player.name == "Rubén Iván Martínez Andrade" ~ "Ronaldinho",
    player.name == "Ronaldo de Assis Moreira" ~ "Rubén",
    player.name == "Thiago Motta" ~ "Thiago Motta",
    player.name == "Mark van Bommel" ~ "Mark van Bommel",
    player.name == "Henrik Larsson" ~ "Henrik Larsson",
    player.name == "José Edmílson Gomes de Moraes" ~ "Edmílson",
    player.name == "Gabriel Francisco García de la Torre" ~ "Gabri",
    player.name == "Santiago Ezquerro Marín" ~ "Santi Ezquerro",
    player.name == "Maximiliano Gastón López" ~ "Maxi López",
    player.name == "Gianluca Zambrotta" ~ "Gianluca Zambrotta",
    player.name == "Eiður Smári Guðjohnsen" ~ "Eiður Guðjohnsen",
    player.name == "Lilian Thuram" ~ "Lilian Thuram",
    player.name == "Javier Pedro Saviola Fernández" ~ "Javier Saviola",
    player.name == "Gnégnéri Yaya Touré" ~ "Yaya Touré",
    player.name == "Bojan Krkíc Pérez" ~ "Bojan",
    player.name == "Eric-Sylvain Bilal Abidal" ~ "Eric Abidal",
    player.name == "Gabriel Alejandro Milito" ~ "Gabriel Milito",
    player.name == "Giovani dos Santos Ramírez" ~ "Giovani dos Santos",
    player.name == "Víctor Vázquez Solsona" ~ "Víctor Vázquez",
    player.name == "Thierry Henry" ~ "Thierry Henry",
    player.name == "José Manuel Pinto Colorado" ~ "José Manuel Pinto",
    player.name == "Daniel Alves da Silva" ~ "Dani Alves",
    player.name == "Sergio Busquets i Burgos" ~ "Sergio Busquets",
    player.name == "Seydou Kéita" ~ "Seydou Kéita",
    player.name == "José Martín Cáceres Silva" ~ "Martín Cáceres",
    player.name == "Gerard Piqué Bernabéu" ~ "Gerard Piqué",
    player.name == "Aliaksandr Hleb" ~ "Aliaksandr Hleb",
    player.name == "Pedro Eliezer Rodríguez Ledesma" ~ "Pedro",
    player.name == "Sergio Rodríguez García" ~ "Rodri",
    player.name == "Rafael Romero Serrano" ~ "Fali",
    player.name == "José Manuel Rueda Sampedro" ~ "José Manuel Rueda",
    player.name == "Zlatan Ibrahimovic" ~ "Zlatan Ibrahimovic",
    player.name == "Dmytro Chygrynskiy" ~ "Dmytro Chygrynskiy",
    player.name == "Maxwell Scherrer Cabelino Andrade" ~ "Maxwell",
    player.name == "Jeffren Isaac Suárez Bermúdez" ~ "Jeffren",
    player.name == "Víctor Sánchez Mata" ~ "Víctor Sánchez",
    player.name == "Thiago Alcântara do Nascimento" ~ "Thiago Alcântara",
    player.name == "David Villa Sánchez" ~ "David Villa",
    player.name == "Javier Alejandro Mascherano" ~ "Javier Mascherano",
    player.name == "Andreu Fontàs Prat" ~ "Andreu Fontàs",
    player.name == "Ibrahim Afellay" ~ "Ibrahim Afellay",
    player.name == "Manuel Agudo Durán" ~ "Nolito",
    player.name == "Marc Bartra Aregall" ~ "Marc Bartra",
    player.name == "Adriano Correia Claro" ~ "Adriano",
    player.name == "Martín Montoya Torralbo" ~ "Martín Montoya",
    player.name == "Jonathan dos Santos Ramírez" ~ "Jonathan dos Santos",
    player.name == "Francesc Fàbregas i Soler" ~ "Cesc Fàbregas",
    player.name == "Alexis Alejandro Sánchez Sánchez" ~ "Alexis Sánchez",
    player.name == "Juan Isaac Cuenca López" ~ "Isaac Cuenca",
    player.name == "Gerard Deulofeu Lázaro" ~ "Gerard Deulofeu",
    player.name == "Cristian Tello" ~ "Cristian Tello",
    player.name == "Sergi Roberto Carnicer" ~ "Sergi Roberto",
    player.name == "Marc Muniesa Martínez" ~ "Marc Muniesa",
    TRUE ~ player.name
  )) %>% 
  ## pass.recipient.name
  mutate(pass.recipient.name = case_when(
    pass.recipient.name == "Oleguer Presas Renom" ~ "Oleguer",
    pass.recipient.name == "Xavier Hernández Creus" ~ "Xavi",
    pass.recipient.name == "Carles Puyol i Saforcada" ~ "Carles Puyol",
    pass.recipient.name == "Anderson Luís de Souza" ~ "Deco",
    pass.recipient.name == "Rafael Márquez Álvarez" ~ "Rafa Márquez",
    pass.recipient.name == "Giovanni van Bronckhorst" ~ "Gio v.Bronckhorst",
    pass.recipient.name == "Samuel Eto'o Fils" ~ "Samuel Eto'o",
    pass.recipient.name == "Víctor Valdés Arribas" ~ "Víctor Valdés",
    pass.recipient.name == "Juliano Haus Belletti" ~ "Juliano Belletti",
    pass.recipient.name == "Ludovic Giuly" ~ "Ludovic Giuly",
    pass.recipient.name == "Andrés Iniesta Luján" ~ "Andrés Iniesta",
    pass.recipient.name == "Ronaldo de Assis Moreira" ~ "Ronaldinho",
    pass.recipient.name == "Lionel Andrés Messi Cuccittini" ~ "Lionel Messi",
    pass.recipient.name == "Fernando Navarro i Corbacho" ~ "Fernando Navarro",
    pass.recipient.name == "Sylvio Mendes Campos Junior" ~ "Sylvinho",
    pass.recipient.name == "Damià Abella Pérez" ~ "Damià",
    pass.recipient.name == "Rubén Iván Martínez Andrade" ~ "Ronaldinho",
    pass.recipient.name == "Ronaldo de Assis Moreira" ~ "Rubén",
    pass.recipient.name == "Thiago Motta" ~ "Thiago Motta",
    pass.recipient.name == "Mark van Bommel" ~ "Mark van Bommel",
    pass.recipient.name == "Henrik Larsson" ~ "Henrik Larsson",
    pass.recipient.name == "José Edmílson Gomes de Moraes" ~ "Edmílson",
    pass.recipient.name == "Gabriel Francisco García de la Torre" ~ "Gabri",
    pass.recipient.name == "Santiago Ezquerro Marín" ~ "Santi Ezquerro",
    pass.recipient.name == "Maximiliano Gastón López" ~ "Maxi López",
    pass.recipient.name == "Gianluca Zambrotta" ~ "Gianluca Zambrotta",
    pass.recipient.name == "Eiður Smári Guðjohnsen" ~ "Eiður Guðjohnsen",
    pass.recipient.name == "Lilian Thuram" ~ "Lilian Thuram",
    pass.recipient.name == "Javier Pedro Saviola Fernández" ~ "Javier Saviola",
    pass.recipient.name == "Gnégnéri Yaya Touré" ~ "Yaya Touré",
    pass.recipient.name == "Bojan Krkíc Pérez" ~ "Bojan",
    pass.recipient.name == "Eric-Sylvain Bilal Abidal" ~ "Eric Abidal",
    pass.recipient.name == "Gabriel Alejandro Milito" ~ "Gabriel Milito",
    pass.recipient.name == "Giovani dos Santos Ramírez" ~ "Giovani dos Santos",
    pass.recipient.name == "Víctor Vázquez Solsona" ~ "Víctor Vázquez",
    pass.recipient.name == "Thierry Henry" ~ "Thierry Henry",
    pass.recipient.name == "José Manuel Pinto Colorado" ~ "José Manuel Pinto",
    pass.recipient.name == "Daniel Alves da Silva" ~ "Dani Alves",
    pass.recipient.name == "Sergio Busquets i Burgos" ~ "Sergio Busquets",
    pass.recipient.name == "Seydou Kéita" ~ "Seydou Kéita",
    pass.recipient.name == "José Martín Cáceres Silva" ~ "Martín Cáceres",
    pass.recipient.name == "Gerard Piqué Bernabéu" ~ "Gerard Piqué",
    pass.recipient.name == "Aliaksandr Hleb" ~ "Aliaksandr Hleb",
    pass.recipient.name == "Pedro Eliezer Rodríguez Ledesma" ~ "Pedro",
    pass.recipient.name == "Sergio Rodríguez García" ~ "Rodri",
    pass.recipient.name == "Rafael Romero Serrano" ~ "Fali",
    pass.recipient.name == "José Manuel Rueda Sampedro" ~ "José Manuel Rueda",
    pass.recipient.name == "Zlatan Ibrahimovic" ~ "Zlatan Ibrahimovic",
    pass.recipient.name == "Dmytro Chygrynskiy" ~ "Dmytro Chygrynskiy",
    pass.recipient.name == "Maxwell Scherrer Cabelino Andrade" ~ "Maxwell",
    pass.recipient.name == "Jeffren Isaac Suárez Bermúdez" ~ "Jeffren",
    pass.recipient.name == "Víctor Sánchez Mata" ~ "Víctor Sánchez",
    pass.recipient.name == "Thiago Alcântara do Nascimento" ~ "Thiago Alcântara",
    pass.recipient.name == "David Villa Sánchez" ~ "David Villa",
    pass.recipient.name == "Javier Alejandro Mascherano" ~ "Javier Mascherano",
    pass.recipient.name == "Andreu Fontàs Prat" ~ "Andreu Fontàs",
    pass.recipient.name == "Ibrahim Afellay" ~ "Ibrahim Afellay",
    pass.recipient.name == "Manuel Agudo Durán" ~ "Nolito",
    pass.recipient.name == "Marc Bartra Aregall" ~ "Marc Bartra",
    pass.recipient.name == "Adriano Correia Claro" ~ "Adriano",
    pass.recipient.name == "Martín Montoya Torralbo" ~ "Martín Montoya",
    pass.recipient.name == "Jonathan dos Santos Ramírez" ~ "Jonathan dos Santos",
    pass.recipient.name == "Francesc Fàbregas i Soler" ~ "Cesc Fàbregas",
    pass.recipient.name == "Alexis Alejandro Sánchez Sánchez" ~ "Alexis Sánchez",
    pass.recipient.name == "Juan Isaac Cuenca López" ~ "Isaac Cuenca",
    pass.recipient.name == "Gerard Deulofeu Lázaro" ~ "Gerard Deulofeu",
    pass.recipient.name == "Cristian Tello" ~ "Cristian Tello",
    pass.recipient.name == "Sergi Roberto Carnicer" ~ "Sergi Roberto",
    pass.recipient.name == "Marc Muniesa Martínez" ~ "Marc Muniesa",
    TRUE ~ pass.recipient.name
  ))
```



# Save clean

```{r}
saveRDS(messi_data_clean, file = here::here("data/messi_data_clean.RDS"))
messi_data_clean <- readRDS(file = here::here("data/messi_data_clean.RDS"))
```


## final 3rd - Messi

```{r}
messi_pass_received_box <- messi_data_clean %>% 
  mutate(pass.outcome.name = fct_explicit_na(pass.outcome.name, "Complete")) %>%
  filter(type.name == "Pass",
         pass.outcome.name == "Complete",
         pass.recipient.id == 5503,
         !play_pattern.name %in% c("From Corner", "From Free Kick",
                                   "From Throw In"),
         pass.end_location.x >= 102 & pass.end_location.y <= 62 &
           pass.end_location.y >= 18) %>% 
  select(player.name, pass.recipient.name, 
         season_id, season_name,
         position.name, position.id,
         location.x, location.y,
         pass.end_location.x, pass.end_location.y,
         contains("pass")) %>% 
  group_by(season_name) %>% 
  add_count(player.name, pass.recipient.name, name = "pass_num") %>% 
  ungroup() %>% 
  mutate(player.name = case_when(
    player.name != "Lionel Messi" ~ 
      glue::glue("{player.name}: {pass_num}")),
    pass.recipient.name = "Lionel Messi") %>% 
  mutate(pass_duo = map2(player.name, pass.recipient.name, ~c(.x, .y)))
```

## Final 3rd - Messi

```{r, fig.height=6, fig.width=8}
messi_pass_nested_box <- messi_pass_received_box %>% 
  group_by(season_name) %>% 
  nest() %>%
  mutate(plot = map2(
    data, season_name,
    ~ ggplot(data = .x, aes(x = pass_duo)) +
      geom_bar(fill = "#a70042") + 
      scale_x_upset(n_intersections = 10,
                    expand = c(0.01, 0.01)) +
      scale_y_continuous(expand = c(0.04, 0.04)) +
      labs(title = glue::glue("Passes to Messi in the Box ({.y})"),
           subtitle = "",
           caption = "Source: StatsBomb",
           x = NULL, y = "Number of Passes") +
      theme_combmatrix(
        text = element_text(family = "Roboto Condensed", 
                            color = "#004c99"),
        plot.title = element_text(family = "Roboto Condensed", size = 20,
                                  color = "#a70042"),
        plot.subtitle = element_text(family = "Roboto Condensed", size = 16,
                                     color = "#004c99"),
        axis.title = element_text(family = "Roboto Condensed", size = 14,
                                  color = "#004c99"), 
        axis.text.x = element_text(family = "Roboto Condensed", size = 12,
                                   color = "#004c99"),
        axis.text.y = element_text(family = "Roboto Condensed", size = 12,
                                   color = "#004c99"),
        panel.background = element_rect(fill = "white"),
        combmatrix.panel.point.size = 4,
        combmatrix.panel.point.color.fill = "#a70042",
        combmatrix.panel.line.color = "#a70042",
        panel.grid = element_line(color = "black"),
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank())))

messi_pass_nested_box$plot[[8]] +
  scale_y_continuous(labels = seq(0, 14, by = 2),
                     breaks = seq(0, 14, by = 2),
                     limits = c(0, 14))
```

### 2004-2005

```{r}
messi_pass_nested_box$plot[[1]] +
  scale_y_continuous(labels = seq(0, 4, by = 2),
                     breaks = seq(0, 4, by = 2),
                     limits = c(0, 4))
```



### 2005-2006

```{r}
messi_pass_nested_box$plot[[2]] +
  scale_y_continuous(labels = seq(0, 6, by = 2),
                     breaks = seq(0, 6, by = 2),
                     limits = c(0, 6))
```



### 2006-2007

```{r}
messi_pass_nested_box$plot[[3]] +
  scale_y_continuous(labels = seq(0, 6, by = 2),
                     breaks = seq(0, 6, by = 2),
                     limits = c(0, 6))
```


### 2007-2008

```{r}
messi_pass_nested_box$plot[[4]] +
  scale_y_continuous(labels = seq(0, 8, by = 2),
                     breaks = seq(0, 8, by = 2),
                     limits = c(0, 8))
```


### 2008-2009

```{r}
messi_pass_nested_box$plot[[5]] +
  scale_y_continuous(labels = seq(0, 18, by = 2),
                     breaks = seq(0, 18, by = 2),
                     limits = c(0, 18))
```

### 2009-2010

```{r, fig.height=6, fig.width=8}
messi_pass_nested_box$plot[[6]] +
  scale_y_continuous(labels = seq(0, 20, by = 2),
                     breaks = seq(0, 20, by = 2),
                     limits = c(0, 20))
```

### 2010-2011

```{r, fig.height=6, fig.width=8}
messi_pass_nested_box$plot[[7]] +
  scale_y_continuous(labels = seq(0, 25, by = 2),
                     breaks = seq(0, 25, by = 2),
                     limits = c(0, 25))
```

### * 2011-2012

```{r}
messi_pass_nested_box$plot[[8]] +
  scale_y_continuous(labels = seq(0, 14, by = 2),
                     breaks = seq(0, 14, by = 2),
                     limits = c(0, 14))
```





## passmaps

```{r}
messi_alves_1112 <- messi_pass_received_box %>% 
  filter(season_name == "2011/2012") %>% 
  mutate(player.name = player.name %>% str_replace_all(., "\\: [0-9]*", "")) %>% 
  filter(player.name == "Dani Alves")
```


```{r}
messi_alves_1112 %>% 
    select(player.name, pass.recipient.name, 
           location.x, location.y, 
           pass.end_location.x, pass.end_location.y,
           pass.length, pass.angle,
           pass.cross, pass.cut_back, 
           pass.through_ball, pass.shot_assist, pass.goal_assist) %>% 
    distinct(player.name, location.x, pass.angle, .keep_all = TRUE)
```


- some passes have NO labels so get filtered out... 

### ggsoccer

```{r}
messi_alves_1112 %>% 
  select(player.name, pass.recipient.name, 
         location.x, location.y, 
         pass.end_location.x, pass.end_location.y,
         pass.length, pass.angle,
         pass.switch, pass.cross, pass.cut_back, 
         pass.through_ball, pass.shot_assist, pass.goal_assist) %>% 
  pivot_longer(-c(player.name, pass.recipient.name,
                  location.x, location.y, 
                  pass.end_location.x, pass.end_location.y,
                  pass.length, pass.angle),
               names_to = "pass_type", values_to = "blah") %>% 
  ## filter out pass.shot_assist and pass.goal_assist as double up
  filter(!pass_type %in% c("pass.shot_assist", "pass.goal_assist"),
         blah == TRUE) %>% 
  ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb) +
  geom_segment(aes(x = location.x, y = location.y, 
                   xend = pass.end_location.x, yend = pass.end_location.y,
                   color = pass_type),      
               lineend = "round", size = 0.6,
               arrow = arrow(length = unit(0.08, "inches"))) + 
  theme_pitch() +
  direction_label(x_label = 60) +
  labs(title = "Completed Box Passes to Messi Leading to Shots (2011/2012)", 
       subtitle = glue::glue("
                             {messi_alves_1112$player.name}: {messi_alves_1112$pass_num}")) +  
  theme(text = element_text(family = "Roboto Condensed"))
```


* Fixed coords

```{r}
messi_alves_1112 %>% 
  select(player.name, pass.recipient.name, 
         location.x, location.y, 
         pass.end_location.x, pass.end_location.y,
         pass.length, pass.angle,
         pass.switch, pass.cross, pass.cut_back, 
         pass.through_ball, pass.shot_assist, pass.goal_assist) %>% 
  pivot_longer(-c(player.name, pass.recipient.name,
                  location.x, location.y, 
                  pass.end_location.x, pass.end_location.y,
                  pass.length, pass.angle),
               names_to = "pass_type", values_to = "blah") %>% 
  ## filter out pass.shot_assist and pass.goal_assist as double up
  filter(!pass_type %in% c("pass.shot_assist", "pass.goal_assist"),
         blah == TRUE) %>% 
  ## swap the y coords
  mutate(rlocation.y = (location.y - 80) * -1,
         rpass.end_location.y = (pass.end_location.y - 80) * -1) %>% 
  ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb) +
  geom_segment(aes(x = location.x, y = rlocation.y, 
                   xend = pass.end_location.x, yend = rpass.end_location.y,
                   color = pass_type),      
               lineend = "round", size = 0.6,
               arrow = arrow(length = unit(0.08, "inches"))) + 
  theme_pitch() +
  direction_label(x_label = 60) +
  labs(title = "Completed Box Passes to Messi Leading to Shots (2011/2012)", 
       subtitle = glue::glue("
                             {messi_alves_1112$player.name}: {messi_alves_1112$pass_num}")) +  
  theme(text = element_text(family = "Roboto Condensed"))
```

### SB pitch

```{r}
create_Pitch() +
  geom_segment(data = messi_alves_1112,
               aes(x = location.x, y = location.y,   
                   xend = pass.end_location.x, yend = pass.end_location.y,
                   color = pass.length),      
               lineend = "round", size = 0.6,
               arrow = arrow(length = unit(0.08, "inches"))) + 
  labs(title = "Completed Box Passes to Messi (2011/2012)", 
       subtitle = glue::glue("Daniel Alves: {messi_alves_1112$pass_num}")) +  
  coord_fixed(ratio = 105/100) +
  theme(text = element_text(family = "Roboto Condensed"))
```

* Fixed coords

```{r}
create_Pitch() +
  geom_segment(data = messi_alves_1112 %>% 
                 mutate(rlocation.y = (location.y - 80) * -1,
                        rpass.end_location.y = (pass.end_location.y - 80) * -1),
               aes(x = location.x, y = rlocation.y,   
                   xend = pass.end_location.x, yend = rpass.end_location.y,
                   color = pass.length),      
               lineend = "round", size = 0.6,
               arrow = arrow(length = unit(0.08, "inches"))) + 
  labs(title = "Completed Box Passes to Messi (2011/2012)", 
       subtitle = glue::glue("Daniel Alves: {messi_alves_1112$pass_num}")) +  
  coord_fixed(ratio = 105/100) +
  theme(text = element_text(family = "Roboto Condensed"))
```

### Dani Alves to Messi box passes

```{r}
messi_alves_1112 %>% 
  mutate(rlocation.y = (location.y - 80) * -1,
         rpass.end_location.y = (pass.end_location.y - 80) * -1) %>%
  ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb) +
  geom_point(x = 80, y = 60) +
  geom_point(x = 0, y = 80, color = "blue") +
  geom_point(x = 0, y = 0, color = "green") +
  geom_point(x = 80, y = 0, color = "red") +
  geom_segment(aes(x = location.x, y = rlocation.y,
                   xend = pass.end_location.x, yend = rpass.end_location.y,
                   color = pass.length),
               lineend = "round", size = 0.6,
               arrow = arrow(length = unit(0.08, "inches"))) +
  theme_pitch() +
  direction_label(x_label = 60) +
  labs(title = "Completed Box Passes to Messi (2011/2012)", 
       subtitle = glue::glue("
                             {messi_alves_1112$player.name}: {messi_alves_1112$pass_num}")) +  
  theme(text = element_text(family = "Roboto Condensed"))
```


```{r}
pitch_custom <- list(
  length = 120,
  width = 80,
  penalty_box_length = 18,
  penalty_box_width = 44,
  six_yard_box_length = 6,
  six_yard_box_width = 20,
  penalty_spot_distance = 12,
  goal_width = 8,
  origin_x = 0,
  origin_y = 0   # change from 80
)

messi_alves_1112 %>% 
  # mutate(rlocation.y = (location.y - 80) * -1,
  #        rpass.end_location.y = (pass.end_location.y - 80) * -1) %>%
  ggplot() +
  annotate_pitch(dimensions = pitch_custom) +
  geom_point(x = 80, y = 60) +
  geom_point(x = 0, y = 80, color = "blue") +
  geom_point(x = 0, y = 0, color = "green") +
  geom_point(x = 80, y = 0, color = "red") +
  geom_segment(aes(x = location.x, y = location.y,
                   xend = pass.end_location.x, yend = pass.end_location.y,
                   color = pass.length),
               lineend = "round", size = 0.6,
               arrow = arrow(length = unit(0.08, "inches"))) +
  theme_pitch() +
  direction_label(x_label = 60) +
  labs(title = "Completed Box Passes to Messi (2011/2012)", 
       subtitle = glue::glue("
                             {messi_alves_1112$player.name}: {messi_alves_1112$pass_num}")) +  
  theme(text = element_text(family = "Roboto Condensed"))
```




### passes comp/imcomp

```{r}
danmessi <- messi_data_clean %>% 
  mutate(pass.outcome = fct_explicit_na(pass.outcome.name, "Complete")) %>%
  filter(season_name == "2011/2012") %>% 
  filter(type.name == "Pass", player.name == "Dani Alves",
         pass.outcome %in% c("Complete", "Incomplete"),
         pass.recipient.name == "Lionel Messi",
         pass.end_location.x >= 102 & pass.end_location.y <= 62 &
           pass.end_location.y >= 18) %>% 
  mutate(rlocation.y = (location.y - 80) * -1,
         rpass.end_location.y = (pass.end_location.y - 80) * -1)

danmessi %>% 
  ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb) +
  geom_segment(data = danmessi, 
               aes(x = location.x, xend = pass.end_location.x, 
                   y = rlocation.y, yend = rpass.end_location.y, 
                   col = pass.outcome), alpha = 0.75,
               key_glyph = "timeseries") +
  geom_point(data = danmessi, 
             aes(x = location.x, y = rlocation.y, 
                 col = pass.outcome), alpha = 0.5,
             show.legend = FALSE) +
  scale_color_manual(values = c("red", "blue")) +
  theme_pitch() +
  direction_label(x_label = 60)
```



### Dani Alves to Messi: by shot-assist

```{r}
messi_alves_1112 %>% 
  mutate(rlocation.y = (location.y - 80) * -1,
         rpass.end_location.y = (pass.end_location.y - 80) * -1) %>% 
  filter(pass.shot_assist == TRUE) %>% 
  ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb) +
  geom_segment(aes(x = location.x, y = rlocation.y,                               
                   xend = pass.end_location.x, yend = rpass.end_location.y),      
               lineend = "round", size = 0.6, color = "blue",
               arrow = arrow(length = unit(0.08, "inches"))) + 
  geom_point(aes(x = location.x, y = rlocation.y)) +
  theme_pitch() +
  direction_label(x_label = 60) +
  labs(title = "Shot Assists to Messi (2011/2012)", 
       subtitle = glue::glue("
                             {messi_alves_1112$player.name}: {messi_alves_1112$pass_num}")) +  
  theme(text = element_text(family = "Roboto Condensed"))
```







## final 3rd - Dani Alves

```{r}
dalves_passes_box <- messi_data_clean %>% 
  mutate(pass.outcome.name = fct_explicit_na(pass.outcome.name, "Complete")) %>%
  filter(type.name == "Pass",
         pass.outcome.name == "Complete",
         player.name == "Dani Alves",
         !play_pattern.name %in% c("From Corner", "From Free Kick",
                                   "From Throw In"),
         pass.end_location.x >= 102 & pass.end_location.y <= 62 &
           pass.end_location.y >= 18) %>% 
  select(player.name, pass.recipient.name, 
         season_id, season_name,
         position.name, position.id,
         location.x, location.y,
         pass.end_location.x, pass.end_location.y,
         contains("pass")) %>% 
  group_by(season_name) %>% 
  add_count(player.name, pass.recipient.name, name = "pass_num") %>% 
  ungroup() %>% 
  mutate(player.name = glue::glue("{player.name}: {pass_num}")) %>% 
  mutate(pass_duo = map2(player.name, pass.recipient.name, ~c(.x, .y)))
```






```{r}
dalves_passes_box %>% 
  filter(season_name == "2011/2012") %>% 
  select(player.name, pass.recipient.name, 
         location.x, location.y, 
         pass.end_location.x, pass.end_location.y,
         pass.length, pass.angle,
         pass.switch, pass.cross, pass.cut_back, 
         pass.through_ball, pass.shot_assist, pass.goal_assist) %>% 
  pivot_longer(-c(player.name, pass.recipient.name,
                  location.x, location.y, 
                  pass.end_location.x, pass.end_location.y,
                  pass.length, pass.angle),
               names_to = "pass_type", values_to = "blah") %>% 
  ## filter out pass.shot_assist and pass.goal_assist as double up
  filter(!pass_type %in% c("pass.shot_assist", "pass.goal_assist"),
         blah == TRUE) %>% 
  ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb) +
  geom_segment(aes(x = location.x, y = location.y, 
                   xend = pass.end_location.x, yend = pass.end_location.y,
                   color = pass_type),      
               lineend = "round", size = 0.6,
               arrow = arrow(length = unit(0.08, "inches"))) + 
  theme_pitch() +
  direction_label(x_label = 60) +
  labs(title = "Completed Box Passes by Dani Alves (2011/2012)") +  
  theme(text = element_text(family = "Roboto Condensed"))
```

